#!/bin/bash
#SBATCH --job-name=dos.job
#SBATCH --output=/home/cpitumpeappu/wireless/code/final/output/dos.out
#SBATCH --error=/home/cpitumpeappu/wireless/code/final/errors/dos.err
#SBATCH --gres=gpu:4
#SBATCH --mem=0

echo "Starting"


# Test Python conda environment
source /home/cpitumpeappu/wireless/code/cse570/bin/activate
echo "venv activated"
python /home/cpitumpeappu/wireless/code/final/code/dos.py


